# Generated by Django 5.2.6 on 2025-09-18 23:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogindexpage_blogpostpage_homepage_intro'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='AboutPage',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
